apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mqtt-topics-api.fullname" . }}-mqtt-logs-api
  labels:
    {{- include "mqtt-topics-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: mqtt_logs_api
spec:
  replicas: {{ .Values.mqtt_logs_api.replicaCount }}
  selector:
    matchLabels:
      {{- include "mqtt-topics-api.labels" . | nindent 6 }}
      app.kubernetes.io/component: mqtt_logs_api
  template:
    metadata:
      labels:
        {{- include "mqtt-topics-api.labels" . | nindent 8 }}
        app.kubernetes.io/component: mqtt_logs_api
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: mqtt-logs-api
          image: {{ include "mqtt-topics-api.image" (dict "context" . "service" .Values.mqtt_logs_api.image.name) }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          volumeMounts:
            - name: {{ .Values.global.sqlite_data.name }} 
              mountPath: {{ .Values.global.sqlite_data.mountPath }}
            - name: config
              mountPath: /app/config
          resources:
            {{- toYaml .Values.mqtt_logger.resources | nindent 12 }}
          env:
            - name: MQTT_BROKER
              value: {{ .Values.env_values.MQTT_BROKER }}
            - name: MQTT_PORT
              value: "5293"
            - name: MQTT_TOPIC
              value: {{ .Values.env_values.MQTT_TOPIC }}
            - name: DB_PATH
              value: {{ .Values.env_values.DB_PATH }}
            - name: UNICORN_PORT
              value: "5283"
            - name: MQTT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.mqtt_secrets.name }}
                  key: MQTT_USER
            - name: MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.mqtt_secrets.name }} 
                  key: MQTT_PASSWORD
      volumes:
        - name: {{ .Values.global.sqlite_data.name }}
          persistentVolumeClaim: 
            claimName: {{ include "mqtt-topics-api.fullname" . }}-sqlite-data-claim
        - name: config
          configMap:
            name: {{ include "mqtt-topics-api.fullname" . }}-config
            items:
              - key: logger
                path: logger.conf

