apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqtt-topics-api.fullname" . }}-mqtt_logs_api_service
  labels:
    {{- include "mqtt-topics-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: mqtt_logs_api
spec:
  type: {{ .Values.mqtt_logs_api.service.type }}
  selector:
    {{- include "mqtt-topics-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: mqtt_logs_api
  ports:
    - name: mqtt_logs_api
      protocol: TCP
      port: {{ .Values.mqtt_logs_api.service.port }}
      targetPort: {{ .Values.mqtt_logs_api.service.targetPort }}
      nodePort: {{ .Values.mqtt_logs_api.service.nodePort }}
